---
- name: "Setup K8S Alias and Auto Completion"
  lineinfile:
    path: "/home/{{ ansible_user }}/.bashrc"
    line: "{{ item }}"
    create: yes
  with_items:
    - "source <(kubectl completion bash)"
    - "alias kc=kubectl"
    - "complete -F __start_kubectl kc"

- name: "Init K8S Master"
  command: "kubeadm init"
  ignore_errors: true

- name: "Create KUBE Config"
  file:
    path: "/home/{{ ansible_user }}/.kube"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: "Copy admin.conf"
  copy:
    src: "/etc/kubernetes/admin.conf"
    dest: "/home/{{ ansible_user }}/.kube/config"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    remote_src: true