---
- name: "Generate Join Command"
  delegate: localhost
  command: "kubeadm token create --print-join-command --ttl=5m"
  register: k8s_join

- name: "Join Cluster"
  command: "{{ k8s_join.stdout }}"